---
- name: Download images
  block:
    - name: debug
      debug:
        msg: "{{ item.key }}  {{ item.value.url }} {{ item.value.checksum }}"
      with_dict: "{{ virt_infra_host_images }}"
      when:
        - inventory_hostname in groups['kvmhost']

    - meta: pause


    ## Download the image if required variables exist
    ## ** DO NOT USE checksum HERE ** (we will do checksums separately)
    ## If the checksum changes down the track it will delete images that don't match
    ## That will be catastrophic for existing guests using it as a backing image
    - name: "KVM host: Download distro disk images"
      get_url:
        url: "{{ virt_infra_distro_image_url }}"
        dest: "{{ hostvars[kvmhost].virt_infra_host_image_path | default(virt_infra_host_image_path) }}/{{ virt_infra_distro_image }}"
        owner: "{{ hostvars[kvmhost].virt_infra_host_image_owner | default('root') }}"
        group: "{{ hostvars[kvmhost].virt_infra_host_image_group | default('qemu') }}"
        mode: "{{ hostvars[kvmhost].virt_infra_host_image_mode | default('0660') }}"
#        seuser: system_u
#        serole: object_r
#        setype: svirt_image_t
      register: result_image_download
      retries: 3
      delay: 5
      delegate_to: "{{ kvmhost }}"
      until: result_image_download is succeeded
      when:
        - inventory_hostname in groups['kvmhost']
        - not result_base_image.stat.exists
        - virt_infra_distro_image_url is defined and virt_infra_distro_image_url
        - virt_infra_distro_image_checksum is defined and virt_infra_distro_image_checksum
      ignore_errors: true
      changed_when: false
      become: true

    - name: debug
      debug: var=result_image_download

    # Check the checksum of the file

    # Move the file in place if success

    # Delete the file if failed


    - name: Validation failures
      debug:
        msg: "{{ validations_failed|default('nothing') }}"
      when:
        - validations_failed is defined and validations_failed
      failed_when: true

  rescue:
    - debug:
        msg: "Play aborted, see errors above"
      changed_when: true

    - meta: end_play
- meta: pause
